version: '3.9'

services:
  db:
    image: postgres:17
    container_name: dev-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: blog_db
    ports:
      - '5432:5432'
    volumes:
      - dev-postgres:/var/lib/postgresql/data

volumes:
  dev-postgres: